// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNz0_WNkKTBiv0QpuDLK4n3oVf8dwiy2I',
    appId: '1:1002614697328:web:1e61b3ad34bae0a5d633b5',
    messagingSenderId: '1002614697328',
    projectId: 'chat-c585b',
    authDomain: 'chat-c585b.firebaseapp.com',
    storageBucket: 'chat-c585b.firebasestorage.app',
    measurementId: 'G-F5W4YGTWTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLY5ohEDPoV6zv15WCUQiaCLA5vX9gfkQ',
    appId: '1:1002614697328:android:661e849e4a940502d633b5',
    messagingSenderId: '1002614697328',
    projectId: 'chat-c585b',
    storageBucket: 'chat-c585b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn1N-D4hPLFd8ANlbprJA9Xo5a26YEIa0',
    appId: '1:1002614697328:ios:ef1247b1af98cfe8d633b5',
    messagingSenderId: '1002614697328',
    projectId: 'chat-c585b',
    storageBucket: 'chat-c585b.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn1N-D4hPLFd8ANlbprJA9Xo5a26YEIa0',
    appId: '1:1002614697328:ios:ef1247b1af98cfe8d633b5',
    messagingSenderId: '1002614697328',
    projectId: 'chat-c585b',
    storageBucket: 'chat-c585b.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNz0_WNkKTBiv0QpuDLK4n3oVf8dwiy2I',
    appId: '1:1002614697328:web:acad0bb603bb8494d633b5',
    messagingSenderId: '1002614697328',
    projectId: 'chat-c585b',
    authDomain: 'chat-c585b.firebaseapp.com',
    storageBucket: 'chat-c585b.firebasestorage.app',
    measurementId: 'G-Y49M1P5W50',
  );
}
